const TOOLS = [
    // ======== FREE TOOLS (80) ========
    { id: 1, name: "APK Permission Matrix", icon: "📱", category: "developer", free: true, desc: "Decompiles APKs and visualizes permission trees and dangerous permissions" },
    { id: 2, name: "Hex File Fingerprinter", icon: "🔬", category: "file", free: true, desc: "Generates SHA-256 + entropy maps of binary files; detects packed sections" },
    { id: 3, name: "Regex Pattern Forge", icon: "⚙️", category: "developer", free: true, desc: "Visual regex builder with real-time matching and multi-language export" },
    { id: 4, name: "Font Glyph Inspector", icon: "🔤", category: "design", free: true, desc: "Renders every Unicode codepoint in uploaded fonts; flags missing glyphs" },
    { id: 5, name: "CSS Cascade Visualizer", icon: "🎨", category: "developer", free: true, desc: "Visual map of selector specificity, inheritance chains, and conflicts" },
    { id: 6, name: "JSON Schema Drafter", icon: "📋", category: "developer", free: true, desc: "Reverse-engineers JSON Schema from sample objects with polymorphism detection" },
    { id: 7, name: "Webhook Replay Studio", icon: "🔁", category: "developer", free: true, desc: "Captures, stores, and replays webhook payloads with header manipulation" },
    { id: 8, name: "Git Commit Message Analyzer", icon: "📊", category: "developer", free: true, desc: "Analyzes commit history for conventional compliance and author stats" },
    { id: 9, name: "Cron Expression Explainer", icon: "⏰", category: "developer", free: true, desc: "Parses cron into human-readable schedules with next-run previews" },
    { id: 10, name: "BaseN Multi-Base Converter", icon: "🔢", category: "math", free: true, desc: "Converts between any base from 2 to 64 with custom alphabet support" },
    { id: 11, name: "Text Entropy Calculator", icon: "🎲", category: "security", free: true, desc: "Measures Shannon entropy; detects pseudo-randomness and weak tokens" },
    { id: 12, name: "SVG Path Optimizer", icon: "📐", category: "design", free: true, desc: "Simplifies SVG paths using Douglas-Peucker algorithm to reduce file size" },
    { id: 13, name: "Image Palette Extractor", icon: "🌈", category: "design", free: true, desc: "Extracts dominant palettes via k-means clustering; exports CSS/SCSS/Tailwind" },
    { id: 14, name: "Color Accessibility Auditor", icon: "♿", category: "design", free: true, desc: "WCAG scoring with 8 color blindness simulations for any color pair" },
    { id: 15, name: "Markdown TOC Generator", icon: "📑", category: "content", free: true, desc: "Auto-generates nested table of contents with anchor links from headings" },
    { id: 16, name: "JWT Decoder & Validator", icon: "🔐", category: "security", free: true, desc: "Decodes, inspects, and validates JWT token payloads and signatures" },
    { id: 17, name: "Hash Diff Explorer", icon: "🔀", category: "security", free: true, desc: "Compares two hash outputs byte-by-byte and identifies divergent bits" },
    { id: 18, name: "ASN.1 Structure Viewer", icon: "📦", category: "file", free: true, desc: "Parses and displays ASN.1 encoded data from certificates and keys" },
    { id: 19, name: "ELF Header Inspector", icon: "🖥️", category: "file", free: true, desc: "Reads ELF binary headers: sections, symbols, and program headers" },
    { id: 20, name: "PE File Analyzer", icon: "🗂️", category: "file", free: true, desc: "Inspects Portable Executable files: imports, exports, and resources" },
    { id: 21, name: "MIME Type Detector", icon: "🏷️", category: "file", free: true, desc: "Detects true MIME type by file signature not just extension" },
    { id: 22, name: "UUID Generator v4/v7", icon: "🆔", category: "developer", free: true, desc: "Generates UUID v4 and v7 with timestamp-based sorting capabilities" },
    { id: 23, name: "QR Code Generator", icon: "📲", category: "developer", free: true, desc: "Creates QR codes with custom colors, logos, and error correction levels" },
    { id: 24, name: "Barcode Generator", icon: "📊", category: "developer", free: true, desc: "Generates Code128, EAN-13, UPC-A, and ISBN barcodes" },
    { id: 25, name: "SSL Certificate Inspector", icon: "🔒", category: "security", free: true, desc: "Examines SSL certificate chain, validity, issuer, and key strength" },
    { id: 26, name: "HTTP Header Analyzer", icon: "🌐", category: "network", free: true, desc: "Explains every HTTP response header and flags security weaknesses" },
    { id: 27, name: "Subnet Calculator", icon: "📡", category: "network", free: true, desc: "CIFR notation calculator with network range and broadcast address" },
    { id: 28, name: "Port Scanner Simulator", icon: "🔌", category: "network", free: true, desc: "Simulates TCP/UDP port scanning with service detection mapping" },
    { id: 29, name: "DNS Record Lookup", icon: "🔍", category: "network", free: true, desc: "Queries A, AAAA, MX, TXT, CNAME, and NS records for any domain" },
    { id: 30, name: "Whois Domain Lookup", icon: "📝", category: "network", free: true, desc: "Shows domain registration details, expiry dates, and nameserver info" },
    { id: 31, name: "Robots.txt Parser", icon: "🤖", category: "network", free: true, desc: "Validates and interprets robots.txt directives for crawl rules" },
    { id: 32, name: "Sitemap Validator", icon: "🗺️", category: "network", free: true, desc: "Checks XML sitemaps for errors, duplicate URLs, and missing tags" },
    { id: 33, name: "Open Graph Previewer", icon: "👁️", category: "content", free: true, desc: "Fetches and previews how any URL appears when shared on social media" },
    { id: 34, name: "Meta Tag Generator", icon: "🏷️", category: "content", free: true, desc: "Generates complete SEO meta tags including Open Graph and Twitter Cards" },
    { id: 35, name: "Slug Generator", icon: "🔗", category: "text", free: true, desc: "Converts any string into URL-safe slugs with multiple language support" },
    { id: 36, name: "Lorem Ipsum Generator", icon: "📄", category: "text", free: true, desc: "Generates placeholder text with options for paragraphs, words, or bytes" },
    { id: 37, name: "Unicode Character Map", icon: "🔣", category: "text", free: true, desc: "Browse all Unicode blocks with copy-to-clipboard for any character" },
    { id: 38, name: "Text Case Converter", icon: "Aa", category: "text", free: true, desc: "camelCase, PascalCase, snake_case, kebab-case, and more conversions" },
    { id: 39, name: "String Similarity Checker", icon: "🔗", category: "text", free: true, desc: "Measures string distance using Levenshtein, Jaro-Winkler, and cosine" },
    { id: 40, name: "Palindrome Detector", icon: "🔄", category: "text", free: true, desc: "Checks if text is palindrome, anagram, or pangram with detailed analysis" },
    { id: 41, name: "Word Frequency Analyzer", icon: "📈", category: "text", free: true, desc: "Counts word frequency, generates word clouds, and finds N-grams" },
    { id: 42, name: "Readability Scorer", icon: "📖", category: "text", free: true, desc: "Flesch-Kincaid, Gunning Fog, and Coleman-Liau readability indices" },
    { id: 43, name: "Diff Text Compare", icon: "📋", category: "text", free: true, desc: "Side-by-side text comparison with highlighted additions and deletions" },
    { id: 44, name: "Markdown to HTML Converter", icon: "📝", category: "developer", free: true, desc: "Live markdown editor with side-by-side HTML preview" },
    { id: 45, name: "HTML to Markdown Converter", icon: "📄", category: "developer", free: true, desc: "Strips HTML tags and converts to clean markdown formatting" },
    { id: 46, name: "YAML to JSON Converter", icon: "🔄", category: "developer", free: true, desc: "Bidirectional YAML and JSON conversion with validation" },
    { id: 47, name: "XML to JSON Converter", icon: "🔄", category: "file", free: true, desc: "Converts XML documents to JSON with attribute mapping options" },
    { id: 48, name: "CSV to JSON Converter", icon: "🔄", category: "developer", free: true, desc: "Upload CSV and convert to JSON array with delimiter options" },
    { id: 49, name: "SQL Formatter", icon: "💾", category: "developer", free: true, desc: "Beautifies and minifies SQL queries with syntax highlighting" },
    { id: 50, name: "XML Formatter", icon: "📋", category: "developer", free: true, desc: "Prettifies and validates XML with tree navigation" },
    { id: 51, name: "Code Minifier", icon: "📦", category: "developer", free: true, desc: "Minifies JavaScript and CSS with dead code elimination" },
    { id: 52, name: "JS Beautifier", icon: "✨", category: "developer", free: true, desc: "Unminifies and reformats obfuscated JavaScript code" },
    { id: 53, name: "JSON Formatter", icon: "📊", category: "developer", free: true, desc: "Pretty-prints JSON with collapsible tree and syntax highlighting" },
    { id: 54, name: "URL Encoder/Decoder", icon: "🔗", category: "text", free: true, desc: "Encodes/decodes URL components, query strings, and path segments" },
    { id: 55, name: "HTML Entity Encoder", icon: "🔤", category: "developer", free: true, desc: "Converts special characters to HTML entities and vice versa" },
    { id: 56, name: "Base64 Image Converter", icon: "🖼️", category: "developer", free: true, desc: "Converts images to base64 strings and base64 back to images" },
    { id: 57, name: "Epoch Timestamp Converter", icon: "🕐", category: "developer", free: true, desc: "Converts Unix timestamps to dates and dates to timestamps in any timezone" },
    { id: 58, name: "Timezone Converter", icon: "🌍", category: "text", free: true, desc: "Convert time between any two time zones with DST awareness" },
    { id: 59, name: "Password Strength Meter", icon: "🔑", category: "security", free: true, desc: "Analyzes password entropy, crack time, and suggests improvements" },
    { id: 60, name: "Bcrypt Hash Generator", icon: "🔐", category: "security", free: true, desc: "Generates and verifies bcrypt hashes with configurable cost factor" },
    { id: 61, name: "HMAC Generator", icon: "🛡️", category: "security", free: true, desc: "Computes HMAC hashes using MD5, SHA1, SHA256, and SHA512" },
    { id: 62, name: "Random Number Generator", icon: "🎲", category: "math", free: true, desc: "Cryptographically secure random numbers in range with distribution" },
    { id: 63, name: "Percentage Calculator", icon: "💯", category: "math", free: true, desc: "Percentage increase, decrease, of total, and difference calculations" },
    { id: 64, name: "Matrix Calculator", icon: "📐", category: "math", free: true, desc: "Add, subtract, multiply, transpose, and find determinants of matrices" },
    { id: 65, name: "Prime Number Checker", icon: "🔢", category: "math", free: true, desc: "Tests primality, finds prime factors, and lists primes in range" },
    { id: 66, name: "Fibonacci Sequence Generator", icon: "🌀", category: "math", free: true, desc: "Generates Fibonacci numbers up to N with golden ratio display" },
    { id: 67, name: "Color Picker & Converter", icon: "🎨", category: "design", free: true, desc: "Pick colors and convert between HEX, RGB, HSL, CMYK, LAB" },
    { id: 68, name: "Gradient Generator", icon: "🌈", category: "design", free: true, desc: "Create linear and radial gradients with CSS code export" },
    { id: 69, name: "Box Shadow Generator", icon: "💡", category: "design", free: true, desc: "Visual box shadow designer with multi-layer support and CSS export" },
    { id: 70, name: "Border Radius Previewer", icon: "⬜", category: "design", free: true, desc: "8-point border radius editor with live preview and CSS output" },
    { id: 71, name: "Flexbox Playground", icon: "📦", category: "design", free: true, desc: "Interactive flexbox property tester with visual layout output" },
    { id: 72, name: "Grid Layout Generator", icon: "🔲", category: "design", free: true, desc: "CSS Grid generator with custom rows, columns, and gap controls" },
    { id: 73, name: "Favicon Generator", icon: "📌", category: "design", free: true, desc: "Generates favicon in multiple sizes from uploaded image with ICO export" },
    { id: 74, name: "CSS Clip Path Maker", icon: "✂️", category: "design", free: true, desc: "Visual editor for CSS clip-path with polygon, circle, and ellipse shapes" },
    { id: 75, name: "Aspect Ratio Calculator", icon: "📺", category: "design", free: true, desc: "Calculate dimensions for any aspect ratio; common presets included" },
    { id: 76, name: "Image Resizer", icon: "🖼️", category: "design", free: true, desc: "Resize images by pixels or percentage; maintain aspect ratio" },
    { id: 77, name: "EXIF Data Viewer", icon: "📷", category: "design", free: true, desc: "Extract camera settings, GPS coordinates, and metadata from photos" },
    { id: 78, name: "Audio Waveform Viewer", icon: "🎵", category: "file", free: true, desc: "Visualize audio file waveforms with zoom and export as PNG" },
    { id: 79, name: "File Size Converter", icon: "💾", category: "file", free: true, desc: "Convert between bytes, KB, MB, GB, TB, and PiB with precision" },
    { id: 80, name: "Text to Binary Converter", icon: "01", category: "text", free: true, desc: "Encode text to binary and decode binary back to text" },

    // ======== PREMIUM TOOLS (20) ========
    { id: 81, name: "AI Code Refactor Engine", icon: "🧠", category: "developer", free: false, desc: "LLM-assisted structural refactoring with PR-ready diff generation" },
    { id: 82, name: "Deep APK Reverse Engineer", icon: "🕵️", category: "security", free: false, desc: "Full APK decompilation pipeline with deobfuscation, string extraction, and vulnerability scanning" },
    { id: 83, name: "Neural Regex Generator", icon: "✨", category: "developer", free: false, desc: "Describe patterns in plain English; AI generates optimized regex with edge-case testing" },
    { id: 84, name: "Database Query Optimizer", icon: "🗄️", category: "developer", free: false, desc: "Analyzes SQL queries against real schema, suggests indexes, predicts execution plans" },
    { id: 85, name: "Contract Clause Analyzer", icon: "📝", category: "content", free: false, desc: "Flags risky legal clauses, compares against standard templates, suggests alternatives" },
    { id: 86, name: "Smart Vulnerability Scanner", icon: "🛡️", category: "security", free: false, desc: "Automated CVE matching, dependency scanning, and risk prioritization dashboard" },
    { id: 87, name: "AI Documentation Writer", icon: "📚", category: "developer", free: false, desc: "Generates API docs, READMEs, and changelogs from codebase analysis" },
    { id: 88, name: "Performance Bottleneck Detector", icon: "⚡", category: "developer", free: false, desc: "Identifies hot paths, memory leaks, and N+1 queries in your application" },
    { id: 89, name: "Binary Obfuscation Analyzer", icon: "🔍", category: "security", free: false, desc: "Detects packing, encryption, and anti-analysis techniques in executables" },
    { id: 90, name: "CI/CD Pipeline Builder", icon: "🔄", category: "developer", free: false, desc: "Visual pipeline designer for GitHub Actions, GitLab CI, and Jenkins" },
    { id: 91, name: "API Contract Generator", icon: "📋", category: "developer", free: false, desc: "Generates Open API 3.0 specs from code annotations with mock server support" },
    { id: 92, name: "Network Packet Decoder", icon: "📡", category: "network", free: false, desc: "Decode raw PCAP files, analyze protocols, and visualize traffic flows" },
    { id: 93, name: "Intelligent Backup Planner", icon: "💾", category: "security", free: false, desc: "Automated backup strategy with RPO/RTO calculations and disaster recovery plans" },
    { id: 94, name: "AI Image Enhancer", icon: "🖼️", category: "design", free: false, desc: "AI-powered upscaling, noise reduction, and detail enhancement for photos" },
    { id: 95, name: "Smart Log File Analyzer", icon: "📊", category: "developer", free: false, desc: "Parse logs from any format, detect anomalies, and generate incident timelines" },
    { id: 96, name: "Code Complexity Profiler", icon: "📈", category: "developer", free: false, desc: "Cyclomatic complexity, cognitive complexity, and technical debt scoring" },
    { id: 97, name: "Advanced Data Pipeline", icon: "🔗", category: "developer", free: false, desc: "Build ETL pipelines with drag-and-drop components and automated testing" },
    { id: 98, name: "Intelligent Test Case Generator", icon: "🧪", category: "developer", free: false, desc: "Generates unit, integration, and edge-case tests from function signatures" },
    { id: 99, name: "AI Security Audit Report", icon: "🔒", category: "security", free: false, desc: "Comprehensive security assessment with OWASP Top 10 and compliance checks" },
    { id: 100, name: "Smart Architecture Diagram", icon: "🏗️", category: "developer", free: false, desc: "Auto-generates infrastructure diagrams from cloud configs and service meshes" }
];

console.log(`Loaded ${TOOLS.length} tools: ${TOOLS.filter(t => t.free).length} free, ${TOOLS.filter(t => !t.free).length} premium`);